### PR TITLE
chore: bump release version

### PR DESCRIPTION
**Pull request by SoloJiang**
miniapp-builder-shared@0.3.0
rax-miniapp-runtime-webpack-plugin@5.0.0
jsx2mp-loader@0.4.33
build-plugin-rax-miniapp-faas@1.0.2
rax-miniapp-config-webpack-plugin@2.2.0
miniapp-webview-config@1.0.0
rax-miniapp-babel-plugins@0.2.0
miniapp-runtime-config@0.4.0
miniapp-compile-config@0.3.0
rax-miniapp-config-webpack-plugin@3.0.0
miniapp-history@0.1.7

### CODE REVIEW

**Comment by ChrisCindy** [comment]
ChangeLog 要补一下

**Comment by cryzzchen** [comment]
build-plugin-rax-miniapp-plugin 这个包的依赖中存在 miniapp-builder-shared，是否需要一起升级依赖呢？ @SoloJiang @ChrisCindy

**Comment by SoloJiang** [comment]
先把这个仓库的发掉那边才能改，保证那边 ci 可以跑过 @cryzzchen

**Comment by cryzzchen** [comment]
> 

啥？build-plugin-rax-miniapp-plugin这个包在这个仓库啊

**Comment by SoloJiang** [comment]
看错了，你说的插件工程，插件工程不在这次升级范围内，还没看能不能跑起来

**Review by cryzzchen — APPROVED** [review]

**Review by ChrisCindy — APPROVED** [review]

**Pull request merged**
